# -*- coding: utf-8 -*-
"""bankingsales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTOyZIdP9Qc1yC75EDaRiGzx1IqDN383
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df=pd.read_csv('/Banking.csv')
df.head(5)

df.shape

df.info()

df.describe()

# Cell 2 - Data summary
col_summary = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "n_missing": df.isna().sum(),
    "pct_missing": (df.isna().mean()*100).round(2),
    "n_unique": df.nunique(dropna=False)
})
display(col_summary.sort_values("pct_missing", ascending=False))

df.columns = [c.strip() for c in df.columns]

numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = [c for c in df.columns if c not in numeric_cols]

print("Numeric cols:", numeric_cols)
print("Categorical cols (sample):", categorical_cols[:10])

for col in numeric_cols:
    plt.figure(figsize=(8,4))
    plt.hist(df[col].dropna(), bins=30)
    plt.title(f"Histogram: {col}")
    plt.xlabel(col)
    plt.ylabel("count")
    plt.grid(alpha=0.3)
    plt.show()

for col in numeric_cols:
    plt.figure(figsize=(8, 2.5))
    plt.plot(df[col].reset_index(drop=True), marker='', linestyle='-', alpha=0.7)
    plt.title(f"Line Plot: {col}")
    plt.xlabel("Customer Index")
    plt.ylabel(col)
    plt.grid(alpha=0.3)
    plt.show()

for col in numeric_cols:
    plt.figure(figsize=(8,2.5))
    plt.boxplot(df[col].dropna(), vert=False)
    plt.title(f"boxplot: {col}")
    plt.xlabel(col)
    plt.show()

top_to_plot = categorical_cols[:6]
for col in top_to_plot:
    vc = df[col].value_counts(dropna=False).iloc[:20]
    plt.figure(figsize=(8,4))
    vc.plot(kind="bar")
    plt.title(f"Top values in '{col}'")
    plt.ylabel("Count")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()

if len(numeric_cols) >= 2:
    corr = df[numeric_cols].corr()
    plt.figure(figsize=(12,8))
    sns.heatmap(corr, annot=True, fmt=".2f", cmap="viridis", linewidths=0.5)
    plt.title("Correlation matrix (numeric columns)")
    plt.xticks(rotation=45, ha="right")
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()
else:
    print("Not enough numeric columns to compute correlation matrix.")

cols_to_plot = ["Estimated Income", "Savings", "Credit Card Balance","Bank Loans","Bank Deposits","Checking Accounts","Saving Accounts"]

plt.figure(figsize=(15, 10))

for i, col in enumerate(cols_to_plot, 1):
    if col in df.columns:
        plt.subplot(len(cols_to_plot), 1, i)
        plt.plot(df[col].reset_index(drop=True), marker='', linestyle='-', alpha=0.7)
        plt.title(f" {col}", fontsize=14)
        plt.xlabel("Customer Index")
        plt.ylabel(col)
        plt.grid(alpha=0.3)
    else:
        print(f"Column '{col}' not found in dataset")

plt.tight_layout()
plt.show()

"""## Insights of EDA:

1. The strongest positive correlation occur among "Bank Deposits" with "Checking Accounts", "Saving Accounts" and "Foreign Currency Account" indicating that customers who maintain high balances in one account type often hold substantial amount/funds across other accounts as well.

"""